version: 2

workflows:
  version: 2
  workflow:
    jobs:
      - test-3.7
      - lint-code

defaults: &defaults
  working_directory: ~/code
  environment:
    STRICT_WARNINGS: '1'
  steps:
  - checkout
  - run:
      name: Test
      command: python setup.py test

jobs:
  test-3.7:
    <<: *defaults
    docker:
    - image: circleci/python:3.7
    
  lint-code:
    working_directory: ~/code
    steps:
    - checkout
    - run:
        name: Install lint tools
        command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install mypy flake8
    - run:
        name: Lint
        command: |
            . venv/bin/activate
            mypy --strict publish_test
            flake8 --ignore='E501' --exclude=__init__.py publish_test
    docker:
    - image: circleci/python:3.7

