version: 2

workflows:
  version: 2
  workflow:
    jobs:
      - test-3.7
      - lint-code
      - deploy:
          requires:
            - test-3.7
            - lint-code
          filters:
            tags:
              only: /^v?[0-9]+(\.[0-9]+)*/
            branches:
              only: /master/

defaults: &defaults
  working_directory: ~/code
  environment:
    STRICT_WARNINGS: '1'
  steps:
  - checkout
  - run:
      name: Test
      command: python setup.py test

jobs:
  test-3.7:
    <<: *defaults
    docker:
    - image: circleci/python:3.7
    
  lint-code:
    working_directory: ~/code
    steps:
    - checkout
    - run:
        name: Install lint tools
        command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install mypy flake8
    - run:
        name: Lint
        command: |
            . venv/bin/activate
            mypy --strict publish_test
            flake8 --ignore='E501' --exclude=__init__.py publish_test
    docker:
    - image: circleci/python:3.7

  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout

      - run:
          name: verify git tag vs. version
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python setup.py verify

      - restore_cache:
          key: publish-dependencies-cache

      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -U twine

      - save_cache:
          key: publish-dependencies-cache
          paths:
            - "venv"

      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "repository = $PYPI_REPO_URL" >> ~/.pypirc
            echo -e "username = $PYPI_USER" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: create packages
          command: |
            python setup.py sdist
      - run:
          name: upload to pypi
          command: |
            . venv/bin/activate
            twine upload dist/*
